codecov:
    status:
        project:
            default:
                target: auto
                threshold: 1%
    require_ci_to_pass: yes
    max_report_age: off

coverage:
    precision: 2
    round: down
    range: "70...100"
    
fixes:
    - "src/::"
